### ISSUE TITLE
Write stories from Medical Notification and Admin components

### ISSUE THREAD

**Issue by hrozan** [MedPassBrasil/replicant#1]
### Atoms
- [ ] Title 
- [ ] Subtitle
- [ ] Badge 
- [ ] Brand 
- [ ] Button
- [ ] Breadcrumb
- [ ] Description
- [ ] List
- [ ] Progress

### Molecules 
- [ ] Card
- [ ] Option
- [ ] SearchField
- [ ] SelectField
- [ ] TextFiled
- [ ] TextBox

### Templates 
- [ ] Col
- [ ] Row
- [ ] Container

**Comment by hrozan** [comment]
> 
<sub>[View in Slack](https://medpassteam.slack.com/archives/CFMG2ENBS/p1561568801005500)</sub>

Teste

**Comment by fsilva3** [comment]
a pedidos do @hrozan
